import type { Metadata } from "next";
import "./globals.css";
import { createClient } from "@/utils/supabase/server";
import { AuthProvider, Company } from "./contexts/authContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	const supabase = await createClient();
	const {
		data: { user },
	} = await supabase.auth.getUser();

	let company: Company | null = null;

	if (user?.email) {
		const domain = user.email.split("@")[1];
		const { data: companyData, error } = await supabase
			.from("users")
			.select("*")
			.eq("domain", domain)
			.single();

		if (!error && companyData) {
			company = companyData as Company;
		}
	}

	return (
		<html lang="pt-BR">
			<body className="antialiased">
				<AuthProvider initialUser={user} initialCompany={company}>
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
